---
title: "P8105 Homework 6"
author: "Quinton Neville"
date: "November 20, 2018"
header-includes: 
  \usepackage{graphicx}
  \usepackage{float}
  \usepackage{amsmath}
output:
   github_document
---

```{r setup, echo = FALSE, warning = FALSE, message = FALSE}
#Load necessary packages
library(tidyverse)
library(readxl)
library(readr)
library(p8105.datasets)
library(patchwork)
library(ggridges)
library(gridExtra)
library(shiny)
library(plotly)
library(broom)
library(scales)
library(purrr)
library(koRpus)

#Controlling figure output in markdown
knitr::opts_chunk$set(
#  fig.height =   
  fig.width = 6,
#  fig.asp = .5,
  out.width = "90%",
#  out.height = 
 fig.align = "center",
  cache = FALSE
)

#Set Theme for ggplot2
theme_set(theme_bw() + theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom"))

#Set Scientific notation output for knitr
options(scipen = 999)

```

#Problem 1

```{r problem_2, warning = FALSE, error = FALSE, message = FALSE}
#Read in the wp homicide data
wp.homicide.df <- read_csv("./data/wp_homicide_data.csv")

#Snag Dimensions and summary
dim.wp.df <- dim(wp.homicide.df)

#Unique City/State locations
unique.locations <- wp.homicide.df %>% distinct(., city, state) %>% nrow() 

#New city_state variable, filtering, and mutating
wp.homicide.df <- wp.homicide.df %>%
  mutate(
    city_state = str_c(city, state, sep = ", "), 
    unsolved = ifelse(disposition == "Closed without arrest" | disposition == "Open/No arrest", TRUE, FALSE)
  ) %>% select(city_state, everything()) %>%
  filter(city_state != "Dallas, TX" & city_state != "Phoenix, AZ" &
         city_state != "Kansas City, MO" & city_state != "Tulsa, AL") %>%
  mutate(
    victim_race = ifelse(victim_race == "White", "white", "non-white") %>%
      as.factor() %>% fct_relevel(., "white", "non-white"),
    victim_age = parse_number(victim_age)
  )

#GLM model Baltimore
baltimore.glm <- wp.homicide.df %>% group_by(city_state) %>% nest() %>% filter(city_state == "Baltimore, MD") %>%
  mutate(glm_model = map(data, ~glm(unsolved ~ victim_age + victim_sex + victim_race, data = .x, family = "binomial")),
         conf_int = map(.x = glm_model, ~confint_tidy(.x, conf.level = 0.95)),
         glm_model = map(glm_model, ~broom::tidy(.x))) %>%
  unnest(., glm_model, conf_int) %>%
  filter(term == "victim_racenon-white") %>%
  select(city_state, estimate, conf.low, conf.high) %>%
  gather(key = type, value = numeric, estimate:conf.high) %>%
  mutate(numeric = exp(numeric))

#GLM all Cities
all.city.glm <- wp.homicide.df %>% group_by(city_state) %>% nest() %>%
  mutate(glm_model = map(data, ~glm(unsolved ~ victim_age + victim_sex + victim_race, data = .x, family = "binomial")),
         conf_int = map(.x = glm_model, ~confint_tidy(.x, conf.level = 0.95)),
         glm_model = map(glm_model, ~broom::tidy(.x))) %>%
  unnest(., glm_model, conf_int) %>%
  filter(term == "victim_racenon-white") %>%
  select(city_state, estimate, conf.low, conf.high) %>%
  mutate(city_state = as.factor(city_state) %>% fct_reorder(., estimate, .desc = FALSE)) %>%
  gather(key = type, value = numeric, estimate:conf.high) %>%
  mutate(numeric = exp(numeric)) %>%
  spread(type, numeric)

```

```{r fig.width = 6, fig.height = 10}
all.city.glm %>%
  ggplot(aes(x = city_state, y = estimate, fill = estimate)) +
  geom_bar(stat = "identity", colour = "black", width = 1, alpha = 0.9) +
  geom_errorbar(aes(x = city_state, ymin = conf.low, ymax = conf.high), colour = "red", size = .9, alpha = 0.5) +
  coord_flip() +
  viridis::scale_fill_viridis(
    option = "magma",
    name = "Multiplicative Odds Increase", 
    discrete = FALSE
  ) +
  labs(
    x = "City",
    y = "Multiplicative Odds Increase",
    title = "Odds of Homocide Unsolved for Non-White Victims"
  ) +
    theme(legend.position = "bottom",
        axis.text.y = element_text(color = "black", 
        size = 10,  hjust = 1) ) +
  scale_y_continuous(breaks = seq(0, 24, 1), sec.axis = dup_axis())
```

```{r}


```